name: golang-lint
on:
  push:
    branches:
      - main
    paths:
      - "golang/**.go"
      - ".github/workflows/golang-lint.yml"
  pull_request:
    paths:
      - "**.go"
      - ".github/workflows/golang-lint.yml"
jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./golang
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: ls
        run: ls -R
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_flags: "--config=./golang/.golangci.yml ./..."
          go_version_file: "./golang/go.mod"
          fail_level: "error"
          reporter: "github-pr-review"
