name: golang-test
on:
  push:
    branches:
      - "main"
    paths:
      - "golang/**.go"
      - ".github/workflows/golang-test.yml"
  pull_request:
    paths:
      - "golang/**.go"
      - ".github/workflows/golang-test.yml"
env:
  CI: true
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./golang
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: ./golang/go.mod
      - name: test
        run: go test ./... -coverprofile=coverage.out
      - name: report coverage
        uses: k1LoW/octocov-action@v1
        with:
          config: ./.octocov.yml
          work-dir: "./golang"
