name: test
on:
  push:
    branches:
      - "main"
  pull_request:
env:
  CI: true
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: ./src/go.mod
      - name: test
        run: go test ./... -coverprofile=coverage.out
      - name: report coverage
        uses: k1LoW/octocov-action@v0
        with:
          config: ./src/.octocov.yml
